### PR TITLE
Fix ASP.NET Core Identity code sample

### PR DESCRIPTION
**Pull request by mderriey**
Very interesting and informative repository, I really liked it.

I noticed an issue in one of the ASP.NET Core Identity code samples in the `readme.md` file.

Also, it mentions to open an issue if someone finds something confusing, but it looks like Issues haven't been enabled on this repo.

Thanks again for the great work

### CODE REVIEW

**Comment by blowdart** [comment]
Weird, issues are definitely turned on in the repo settings :(

**Comment by mderriey** [comment]
I can see them now. Maybe I wasn't awake enough then. Do you want me to create an issue and link it to this PR? (assuming you'd be happy to take it)

**Comment by blowdart** [comment]
Naw, it's fine, I'm not that formal on here. I'll give the PR the once over when I'm fully awake in a bit :)

**Comment by mderriey** [comment]
Sweet, thanks.

**Comment by mderriey** [comment]
I got it, I was having a look on my fork of this repo for issues :zzz:

**Comment by blowdart** [comment]
Done, and thanks :)

**Pull request merged**
